version: "3.8"

services:
  app:
    build: .
    container_name: blazebuy_app
    image: skyli997/blazebuy:v1.0.0
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: blazebuy_db
    ports:
      - "8000:8000"
